# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: AeroLP_Contenidos_production
  username: root
  password: 
  host: localhost

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
  database: Aerolp_test